import base64
from pathlib import Path

# İkon dizinini oluştur
icons_dir = Path("icons")
icons_dir.mkdir(exist_ok=True)

# İkonlar için base64 kodları
icons = {
    "save": """
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABhSURBVDiNY2AYBYMPMDIyMjAyMv4n1wBGRkYGJiYmBkZGRgYmJiaSNTMxMTEwMzOT5B1GRkYGFhYWkgwgywBGRkYGVlZWwgYwMjIysLGxkWQzIyMjAzs7O+WJcdQABgYAJ6MJYfYrP7QAAAAASUVORK5CYII=
    """,
    "delete": """
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABtSURBVDiNxZNBCsAgDATXtP7/yXvqoYW2pYl6EHEPQdidJIqZ4W+JCMwMqgoAICJwzgEAzAwiAu89QgjIOWOt9VhrIaWEGCN677DWopSCnDPMDNZaEBFCCDjnUGvFOQfee5gZiAhm9v4Rd+UBwPgNYf9wJEQAAAAASUVORK5CYII=
    """,
    "edit": """
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABtSURBVDiNxZExDoAwCEVfG+9/ZOegg0ox1cHEd5CQ8P4PAWaGv0VE4JwDAKgqUkoAAO89zAwiglIKcs5Ya6HWilIKYozovWOMAWstWmuIMcLMYK0FEaGUgnMOvXf03uG9h5mBiGBm7x9xVx6kFQ1hPsKgfwAAAABJRU5ErkJggg==
    """,
    "search": """
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABxSURBVDiNxZFBDoAgDAQXjP9/snfCAQyBVg+EeWiT7c5uKjPD3yIicM4BAFQVKSUAgPceZgYRQa0VJWestdBaQ60VKSWMMTDnxBgD1lqUUhBjhJnBWgsiQq0Vzjn03jHnRO8d3nuYGYgIZvb+EXflAcbDDWFCwGphAAAAAElFTkSuQmCC
    """,
    "report": """
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABxSURBVDiNxZExDoAwCEVfG+9/ZOegg0ox1cHEd5CQ8P4PAWaGv0VE4JwDAKgqUkoAAO89zAwiglIKcs5Ya6HWilIKYozovWOMAWstWmuIMcLMYK0FEaGUgnMOvXf03uG9h5mBiGBm7x9xVx6kFQ1hPsKgfwAAAABJRU5ErkJggg==
    """,
    "settings": """
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABxSURBVDiNxZExDoAwCEVfG+9/ZOegg0ox1cHEd5CQ8P4PAWaGv0VE4JwDAKgqUkoAAO89zAwiglIKcs5Ya6HWilIKYozovWOMAWstWmuIMcLMYK0FEaGUgnMOvXf03uG9h5mBiGBm7x9xVx6kFQ1hPsKgfwAAAABJRU5ErkJggg==
    """,
    "backup": """
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABxSURBVDiNxZExDoAwCEVfG+9/ZOegg0ox1cHEd5CQ8P4PAWaGv0VE4JwDAKgqUkoAAO89zAwiglIKcs5Ya6HWilIKYozovWOMAWstWmuIMcLMYK0FEaGUgnMOvXf03uG9h5mBiGBm7x9xVx6kFQ1hPsKgfwAAAABJRU5ErkJggg==
    """,
    "user": """
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABxSURBVDiNxZExDoAwCEVfG+9/ZOegg0ox1cHEd5CQ8P4PAWaGv0VE4JwDAKgqUkoAAO89zAwiglIKcs5Ya6HWilIKYozovWOMAWstWmuIMcLMYK0FEaGUgnMOvXf03uG9h5mBiGBm7x9xVx6kFQ1hPsKgfwAAAABJRU5ErkJggg==
    """,
    "test": """
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABxSURBVDiNxZExDoAwCEVfG+9/ZOegg0ox1cHEd5CQ8P4PAWaGv0VE4JwDAKgqUkoAAO89zAwiglIKcs5Ya6HWilIKYozovWOMAWstWmuIMcLMYK0FEaGUgnMOvXf03uG9h5mBiGBm7x9xVx6kFQ1hPsKgfwAAAABJRU5ErkJggg==
    """
}

# Her bir ikonu kaydet
for name, data in icons.items():
    # Base64 kodunu temizle
    data = data.strip().replace("\n", "").replace(" ", "")
    
    # Base64'ten binary'ye çevir
    binary_data = base64.b64decode(data)
    
    # Dosyaya kaydet
    with open(icons_dir / f"{name}.png", "wb") as f:
        f.write(binary_data) 